### PR TITLE
Fix Windows

### LINKED ISSUE #205: Building with 3.0.2 fails on Windows if there's a `build-figma-plugin.ui.cjs` file in the repo
I think this is #77 all over again.  The `build-figma-plugin.ui.cjs` file is just this:

```js
module.exports = (buildOptions) => ({
	...buildOptions,
	keepNames: true,
});
```

When it's in the main directory, `npm run build` fails with this error:

```sh
info Typechecking...
success Typechecked in 2.048s
info Building...
error esbuild error
    Only URLs with a scheme in: file, data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
npm ERR! Lifecycle script `build` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: fwidgets-test-plugin@0.0.1 
npm ERR!   at location: C:\...\test 
```

When the config file is removed, the build works, but the plugin doesn't, because it needs to pass `keepNames: true` to esbuild.  (As an aside, it would be nice if this sort of config, as well as the manifest, could be passed on the command line, which would then avoid this problem.)

### PR DESCRIPTION
**Pull request by TheUltDev**
Fixes #205.

This change appends the `file://` protocol to windows paths to the error below
(technically we let `pathToFileURL` from `node:url` do the work)
```
ESBuild: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader.
On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
```

### CODE REVIEW

**Comment by TheUltDev** [comment]
@yuanqing this is ready (no more commits expected)

**Comment by TheUltDev** [comment]
I'm getting errors loading CSS Modules but I can't tell if that's related to these changes or it's been broken on Windows.
I'm also working with a forked copy of the UI library so that might be it. Would be helpful for others to verify.

Should be safe to merge in though for people to test, as currently Windows doesn't work at all right now.

```
ERROR: [plugin: css-modules] CSS file not found: !../css/base.css
```

**Comment by XmlmXmlmX** [comment]
I need this, please

File: packages/build/src/utilities/build-bundles-async/build-bundles-async.ts [hunk 1]
```diff
@@ -16,6 +18,8 @@ import { importFresh } from '../import-fresh.js'
 import { esbuildCssModulesPlugin } from './esbuild-css-modules-plugin.js'
 import { esbuildPreactCompatPlugin } from './esbuild-preact-compat-plugin.js'
 
+const isWindows = platform() === 'win32'
```
Comment (fwextensions) [inline packages/build/src/utilities/build-bundles-async/build-bundles-async.ts:21]: This is probably a dumb question, as I haven't done any platform-specific node development, but I assume this is `win32` even on 64-bit OSes?

**Comment by JanJankowskiEvinced** [comment]
@yuanqing Can we please get this PR merged? It's a major blocker in upgrading to the newest version for windows users
